### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by jrdnr** [IsaacGood/Upgrade-Windows-to-Current-Build-Powershell#1]
I know you often offer your scripts to other MSPs to be helpful however per Github's kb on licensing a repository (https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)

>You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The [Open Source Guide](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) provides additional guidance on choosing the correct license for your project.

Would you consider adding something like the MIT license so we are technically allowed to use the code?

**Comment by IsaacGood** [comment]
Done
